name: CI Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend Docker image
        run: docker build -t agentic-backend ./backend

      - name: Build frontend Docker image
        run: docker build -t agentic-frontend ./frontend
